# Site specific settings
title: "TheRomanXpl0it"
name: "TheRomanXpl0it"
keywords: "CTF, Hacking, Sapienza"
description: "CTF team composed of students of Sapienza, University of Rome and CyberChallengeIT entrants."
#cover: "/assets/img/cover.svg"

# Site general settings
lang: "en"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: theromanxpl0it
twitter: TheRomanXpl0it
#facebook: 
github: TheRomanXpl0it
#google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
