theme: jekyll-theme-minimal
title: TheRomanXpl0it
description: CTF Team composed by students of Sapienza University of Rome and alumns of CyberChallenge.IT.
avatar: https://avatars3.githubusercontent.com/u/32163043?v=4&s=200
